//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectionManagerExample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelectionManagerExample.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Geometry.
        /// </summary>
        public static string AskForGeometry {
            get {
                return ResourceManager.GetString("AskForGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Selection.
        /// </summary>
        public static string BoxSelection {
            get {
                return ResourceManager.GetString("BoxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Selection Window Inside Geometry.
        /// </summary>
        public static string BoxSelectionInside {
            get {
                return ResourceManager.GetString("BoxSelectionInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Selection Successful.
        /// </summary>
        public static string BoxSelectionSuccessful {
            get {
                return ResourceManager.GetString("BoxSelectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Count.
        /// </summary>
        public static string CountOfSelection {
            get {
                return ResourceManager.GetString("CountOfSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example complete.
        /// </summary>
        public static string ExampleComplete {
            get {
                return ResourceManager.GetString("ExampleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Moldbase.mcx-8 drawing (see PDF document).
        /// </summary>
        public static string MissingDrawing {
            get {
                return ResourceManager.GetString("MissingDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Selected.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Line.
        /// </summary>
        public static string SelectALine {
            get {
                return ResourceManager.GetString("SelectALine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select An Arc.
        /// </summary>
        public static string SelectAnArc {
            get {
                return ResourceManager.GetString("SelectAnArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Any Geometry.
        /// </summary>
        public static string SelectAnyGeometry {
            get {
                return ResourceManager.GetString("SelectAnyGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Point.
        /// </summary>
        public static string SelectAPoint {
            get {
                return ResourceManager.GetString("SelectAPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Selected!.
        /// </summary>
        public static string SelectedArc {
            get {
                return ResourceManager.GetString("SelectedArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Selected!.
        /// </summary>
        public static string SelectedLine {
            get {
                return ResourceManager.GetString("SelectedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Selected!.
        /// </summary>
        public static string SelectedPoint {
            get {
                return ResourceManager.GetString("SelectedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Successful!.
        /// </summary>
        public static string SelectionSuccessful {
            get {
                return ResourceManager.GetString("SelectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Multiple Geometries.
        /// </summary>
        public static string SelectMultipleGeometry {
            get {
                return ResourceManager.GetString("SelectMultipleGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Geometry Selected!.
        /// </summary>
        public static string UnknownGeometry {
            get {
                return ResourceManager.GetString("UnknownGeometry", resourceCulture);
            }
        }
    }
}
